__lang__ = {
    "ServerIP": "服务器IP :",
    "Port": "端口 :",
    "PS4IP": "PS4 IP :",
    "Task": "任务",
    "ImportPKG": "导入PKG",
    "Stop": "停止任务",
    "Send": "发送 !",
    'Check':'测试',
    'Url':'在浏览器中打开',

    "MoveUp": "上移一项",
    "MoveDown": "下移一项",
    "Skip": "排除列队",
    "Join": "加入列队",
    "Delete": "删除这些",
    "ClearAll": "清空所有",
    "OpenFolder": "打开所在文件夹",

    "#": "#",
    "Type": "类型",
    "Version": "版本",
    "Title ID": "ID",
    "Title": "标题",
    "File name": "文件名",
    "File Size": "大小",
    "Status": "状态",
    "Path": "路径",

    'Scanning': '正在搜寻',
    'No find': '未找到',
    'Sending': '正在传输',
    'success': '完成',
    'Canceled': '已取消',
    'Ready...': '就绪...',
    " Skip ": "跳过",
    'Error:{}': '错误：{}',
    'Has been installed':'游戏已存在',
    'Task does not exist':'任务不存在',
    '----': '列队中',
    '{} / {} (Remaining {} minute {} seconds, Speed: {}MB/S)': '{} / {} (剩余 {}分钟 {}秒, 速度 {}MB/S)',
    'No response': '未响应',
    'Remote Package Installer': 'Remote Package Installer 未响应，请尝试在PS4中重新启动应用',
    'The PS4 application is suspended or not responding. Please click here to try again ({})':'PS4中的应用程序被挂起或无响应，请单击此处重试 ({})'
}